site_url: https://webssh.net
site_name: iOS & iPadOS SSH client - WebSSH
theme:
  name: material
  logo: images/webssh.png
  favicon: images/favicon.ico
  font: false
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/isontheline/pro.webssh.net
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arnaud-mengus
plugins:
  - search
  - git-revision-date-localized:
      type: date
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg